[project]
name = "django-database-orm"
version = "0.1.0"
description = "Exploring django ORM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "pipdeptree>=2.26.1",
]
